[package]
name = "hdn"
version = "1.1.0"
authors = ["Anastasia Medvedeva <mailanastasia7@gmail.com>"]

[dependencies]
threadpool = "1.0"
serde_json = "1.0"
lazy_static = "1.4.0"
chrono = "0.4"
log = "0.4"
env_logger = "0.10"
csv = "1.1.6"
serde = { version = "1.0.148", features = ["derive"] }
